#!/bin/sh

# build release client
# js minification
# replace 127.0.0.1 => castles.rknrl.ru in vk.html, ok.html, mm.html

cp -a ~/dev/rknrl/castles/client/client-web/src/main/www/. ~/dev/rknrl/castles-deploy/castles-client/www &&
cp ~/dev/rknrl/castles/client/client-web/target/castles-web.swf ~/dev/rknrl/castles-deploy/castles-client/www/game.swf &&

cd ~/dev/rknrl/castles-deploy/castles-client/www &&
git add * &&
git commit -m "update version" &&
git push

#ssh castles@castles-static.rknrl.ru
#cd /var/castles/client/
#sudo -E git pull
#sudo service nginx restart
