#!/bin/sh

SWF_NAME="game7.swf"

# build client-web.swf via ant
cd client/ &&

ant -buildfile build-web.xml castles-web-swf &&

# clear out folder

rm -rf ~/dev/rknrl/castles-deploy/castles-client/www/* &&

# copy client-web.swf to out folder

cp ~/dev/rknrl/castles/client/target/client-web.swf ~/dev/rknrl/castles-deploy/castles-client/www/${SWF_NAME} &&

# copy html files to out folder

cp -a ~/dev/rknrl/castles/client/client-web/src/main/www/. ~/dev/rknrl/castles-deploy/castles-client/www &&

# www folder

cd ~/dev/rknrl/castles-deploy/castles-client/www &&

# replace 127.0.0.1 by castles.rknrl.ru in html files

sed -i.bak "s/127\.0\.0\.1/castles\.rknrl\.ru/g" *.html &&

# replace http port 8080 by 80 in html files

sed -i.bak "s/8080/80/g" *.html &&

# replace game.swf by ${SWF_NAME} in html files

sed -i.bak "s/game.swf/${SWF_NAME}/g" *.html &&

# delete sed *.bak files

rm -rf ~/dev/rknrl/castles-deploy/castles-client/www/*.bak &&

# commit changes

git add * &&
git diff --cached &&
git commit -m "update version" &&
git push

#ssh castles@rknrl.ru
#cd /var/castles-client/
#sudo -E git pull && sudo service nginx restart
