#!/bin/sh

# Generate java and action-script dto classes by protobuf

project="/Users/tolyayanot/dev/rknrl/castles"
rknrl_core="/Users/tolyayanot/dev/rknrl/core"

proto_dir="${project}/server/src/main/protobuf"
as3_out="${project}/client/client-base/src/main/flex/"

java -Xmx512M -XX:MaxPermSize=256M -jar ~/Library/Caches/IntelliJIdea14/sbtexe/sbt-launch-0.13.0.jar clean
java -Xmx512M -XX:MaxPermSize=256M -jar ~/Library/Caches/IntelliJIdea14/sbtexe/sbt-launch-0.13.0.jar protobuf:protobufScalaGenerate

rm -rf ${as3_out}/ru/rknrl/dto/*

protoc \
--as3_out=${as3_out} \
--plugin=protoc-gen-as3=${rknrl_core}/dto/protoc-gen-as3/protoc-gen-as3 \
--proto_path=${proto_dir} \
${proto_dir}/auth.proto \
${proto_dir}/common.proto \
${proto_dir}/account.proto \
${proto_dir}/game.proto \
${proto_dir}/admin.proto

