#!/bin/sh

# Generate scala and action-script rmi by rknrl-rmi

project="/Users/tolyayanot/dev/rknrl/castles"
rknrl_core="/Users/tolyayanot/dev/rknrl/core"

interfaces_dir="${project}/server/src/main/scala/ru/rknrl/castles/rmi/"
scala_out="${project}/server/src/generated/scala/"
as3_out="${project}/client/client-base/src/generated/flex/"
package_out="ru.rknrl.rmi"

rm -rf ${scala_out}/ru/rknrl/rmi/*

${rknrl_core}/rmi/rmi-gen/rmi-gen \
scala \
${scala_out} \
${package_out} \
${interfaces_dir}

rm -rf ${as3_out}/ru/rknrl/rmi/*

${rknrl_core}/rmi/rmi-gen/rmi-gen \
as \
${as3_out} \
${package_out} \
${interfaces_dir}

${rknrl_core}/rmi/rmi-gen/rmi-gen \
as-events \
${as3_out} \
${package_out} \
${interfaces_dir}

