#!/bin/bash

case $1 in
    start)
        /bin/bash /usr/local/bin/castles-start
    ;;
    stop)
        /bin/bash /usr/local/bin/castles-stop
    ;;
    restart)
        /bin/bash /usr/local/bin/castles-stop
        /bin/bash /usr/local/bin/castles-start
    ;;
esac
exit 0
